---
apiVersion: v1
kind: Service
metadata:
  name: spyglass
  labels:
    {{- include "spyglass.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "spyglass.selectorLabels" . | nindent 4 }}
